## Elimina toda a mensgem de erro gigantesca da pagina deixando somente a mensagem 404
server:
  error:
    include-stacktrace: on_param

##Conectando ao banco de dados
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?&allowPublicKeyRetrieval=true
    username: root
    password: kashinho123
  jpa:
    hibernate:
      ddl-auto: update